#!/bin/sh
if [ -d /docs ]
then
        printf '###############################################################\n'
        printf 'point your browser at http://127.0.0.1:%s\n' $PORT
        printf 'you may need to wait a few seconds for mkdocs to initialise\n'
        printf '###############################################################\n\n'
	cd /docs && mkdocs serve -a 0.0.0.0:$PORT
else
	printf "Run this docker image with\n" >&2
	printf "\tdocker run -it --rm -v \$(pwd):/docs -p 8888:8888 -e PORT=8888 kxsys/docs\n\n" >&2
	exit 1
fi
